on:
  push:
    branches:
    - master

jobs:
  build:
    name: Deploy DogHouseApi Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kthompso/dog-house-api
          tags: latest
